AllCops:
  TargetRubyVersion: 3.1

inherit_gem:
  rubocop-espago: rubocop.yml

Lint/BooleanSymbol:
  Enabled: false

Lint/MissingSuper:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Style/YodaExpression:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Style/RaiseArgs:
  Enabled: false
